Fix compile error on Windows
webserver.cpp(194): error C4996: 'close': The POSIX name for this item
is deprecated. Instead, use the ISO C and C++ conformant name: _close.
See online help for details.