Fix compile error
webserver.cpp(181): error C4996: 'read': The POSIX name for this item
is deprecated. Instead, use the ISO C and C++ conformant name: _read.
See online help for details.